### ISSUE TITLE
Some elements have bad colours

### ISSUE THREAD

**Issue by rroberrt** [CTemplar/webclient-themes#2]
Referring to Oled Grey specifically, if I hover my cursor over the sender or receiver in the header of an email, it becomes nearly as black as the background, which makes it unreadable.

**Comment by OneWhiteBird** [comment]
I've verified the issue in my end!

I'll fix it shortly.

Thanks for your feedback!

**Comment by OneWhiteBird** [comment]
Fixed.

Thanks again for reporting!
